game/models.py
from datetime import datetime

from game import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):

    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    last_seen = db.Column(db.DateTime)

    def __repr__(self):
        return f'User({self.id}, {self.username}, {self.email}, {self.password}, {self.image_file})'

game/user/forms.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Length, Email, ValidationError
from game.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired(), Length(min=4, max=20)])
    email = StringField('Емайл', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Войти')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            flash('Это имя уже занято. Пожалуйста, выберите другое', 'danger')
            raise ValidationError('That username is taken. Please choose a different one')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            flash('Этот емайл уже занят. Пожалуйста, введите другой', 'danger')
            raise ValidationError('That email is taken. Please choose a different one')


class LoginForm(FlaskForm):
    email = StringField('Емайл', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

game/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate


db = SQLAlchemy()
bcrypt = Bcrypt()
migrate = Migrate()

login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('settings.py')
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)

    from game.main.routes import main
    from game.user.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)


    return app

game/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('index.html', title='Главная')

game/user/routes.py
import os
import shutil
from datetime import datetime

from flask import Blueprint, render_template, flash, url_for
from flask_login import current_user, logout_user, login_required
from werkzeug.utils import redirect

from game import bcrypt, db
from game.models import User
from game.user.forms import RegistrationForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        full_path = os.path.join(os.getcwd(), 'game/static', 'profile_pics', user.username)
        if not os.path.exists(full_path):
            os.mkdir(full_path)
        shutil.copy(f'{os.getcwd()}/game/static/profile_pics/default.jpg', full_path)
        flash('Ваш аккаунт был создан. Вы можете войти на блог', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form, title='Регистрация', legend='Регистрация')


@users.route('/login', methods=['GET', 'POST'])
def login():
    return 'hello'


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    return render_template('account.html')


@users.route('/logout')
def logout():
    current_user.last_seen = datetime.now()
    db.session.commit()
    logout_user()
    return redirect(url_for('main.home'))

game/templates/account.html
{% extends 'base.html' %}


{% block content %}

{% endblock content %}

game/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/media_css.css')}}">
                <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">


  {% block title %}

      {% if title %}
        <title>Flask - {{ title }}</title>
      {% else %}
        <title>Flask Blog</title>
      {% endif %}

  {% endblock title %}

</head>

<body>

<div class="wrapper">

{% block menu %}
<header class="header">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
    </div>

    <ul class="main_menu">

            <li><a href="{{ url_for('main.home') }}">Главная</a></li>
            <li><a href="{{ url_for('user.register') }}">Регистрация</a></li>
            <li><a href="{{ url_for('user.login') }}">Войти</a></li>
            <li><a href="{{ url_for('main.blog') }}">Игра</a></li>
            <li><a href="{{ url_for('user.account') }}">Аккаунт</a></li>
            <li><a href="{{ url_for('users.logout') }}">Выход</a></li>

    </ul>

</header>
{% endblock menu %}


    <div class="content">

            {% block content %}
            {% endblock content %}

    </div>


{% block main_page %}

{% endblock main_page %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

{% block footer %}

    <footer class="footer">Все права защищены!<br>
        &#169; Терехов Михаил 2021

    </footer>

{% endblock footer %}
</div>
</body>
</html>

game/templates/blog.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

game/templates/index.html
{% extends 'base.html' %}


{% block main_page %}

<div class="wrapper">
    <div class="empty_block"></div>
</div>

{% endblock main_page %}

game/templates/login.html
{% extends 'base.html' %}

{% block content %}

{{ result }}

{% endblock %}

game/templates/register.html
{% extends 'base.html' %}

{% block content %}

<div class="register_form">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
        <legend class="legend">{{ legend }}</legend>

        {% if form.username.errors %}
        {{ form.username(class='form-post-title is-invalid', placeholder='Имя пользователя') }}
        <div class="invalid-feedback">
            {% for errors in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class='form-post-title', placeholder='Имя пользователя') }}
        {% endif %}

        {% if form.email.errors %}
        {{ form.email(class='form-post-title is-invalid', placeholder='Емайл') }}
        <div class="invalid-feedback">
            {% for errors in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class='form-post-title', placeholder='Емайл') }}
        {% endif %}

        {% if form.password.errors %}
        {{ form.password(class='form-post-title is-invalid', placeholder='Пароль') }}
        <div class="invalid-feedback">
            {% for errors in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-post-title', placeholder='Пароль') }}
        {% endif %}

        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class='form-post-title is-invalid', placeholder='Подтвердите пароль') }}
        <div class="invalid-feedback">
            {% for errors in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class='form-post-title', placeholder='Подтвердите пароль') }}
        {% endif %}


        <div class="form-group_button">
           <div class="btn">
                {{ form.submit(class='btn_sign_in') }}
           </div>
              <small class="text-muted">
            Уже есть аккаунт? <a class='ml-2' href="{{ url_for('users.login')}}">Войти</a>
        </small>
        </div>

    </form>
    <div class="border-top">

    </div>
</div>


</div>

{% endblock content%}

game/templates/rezerv/gg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Правила</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="gg.css">
    <script type="text/javascript" src="gg.js"></script>
</head>
<body>
<div id="gradient" />
<h1 align="center"> Правила игры</h1>
<img src="1623101254_20-phonoteka_org-p-tekstura-shashki-krasivo-24.jpg" height="100">
<ul>
    <li>Игра ведётся на доске 8х8 клеток, только на черных ячейках
    <li>Шашки в начале игры занимают первые три ряда с каждый стороны
</ul>
</body>
</html>

game/templates/rezerv/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Это мой сайт</title>
    <meta http-equiv="Content-Type" content="text/html"; charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="in.css">
</head>
<body>
<div class="topnav">
    <a href="gg.html">Правила игры</a>
    <a href="log.html">Войти</a>
</div>
</body>
</html>

game/templates/rezerv/log.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Войти</title>
</head>
<body>
<form action="handler.php">
   <p><strong>Логин:</strong>
    <input maxlength="25" size="40" name="login"></p>
   <p><strong>Пароль:</strong>
    <input type="password" maxlength="25" size="40" name="password"></p>
    <p><input type="button" value=" войти "></p>
    <p><a href="register.html"><input type="button" value=" регистрация "> </a></p>
</form>
</body>
</html>

game/templates/rezerv/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма регистрации</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<h1>
<form action="action_page.php">
  <div class="container">
    <h1>Register</h1>
    <hr>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
    <hr>

    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
    <button type="submit" class="registerbtn">Register</button>
  </div>

  <div class="container signin">
    <p>Already have an account? <a href="хуй.html">Sign in</a>.</p>
  </div>
</form>
</h1>
</body>
</html>